# Site settings
title: BMW-Guys | Stories about some BMW guys
description: '沒看見嗎？寫的清清楚楚，別摸我。'
keywords: '寶馬人'
url: 'https://je-pense.github.io/BMW-Guys/'
author:
  name: '阿甘'
  email: 'winwinsfu@gmail.com'
  url: 'https://je-pense.github.io/BMW-Guys/'

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: '1.0'

# Options
custom_header: false
custom_nav_footer: false
reverse: false
